name: Yakubi Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Runner works!"
